### ISSUE TITLE
livestats.py error prior weeks

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#31]
I have created a league I am using for testing - 2 teams, defined scoring, set line up for week 1, 2, 3 but when I try to load the stats for prior weeks I keep getting an error - the current week stats (3) are working fine, but no matter what I try for -week 1 or 2 I get the following:

]$ python livestats.py -year 2017 -week 1 -all -recalc_all
Udpating NFL Statistics (2017-09-24 17:32:46)

Reading NFL stats for Week 1
Traceback (most recent call last):
  File "livestats.py", line 656, in <module>
    main()
  File "livestats.py", line 46, in main
    update_games(year, week, weektype, args.all)
  File "livestats.py", line 67, in update_games
    (live_changes_made, livegamecount) = update_nfl_statistics(year, week, weektype, update_all)
  File "livestats.py", line 109, in update_nfl_statistics
    games = nflgame.games(int(year), week=int(week), kind=weektype)
  File "/usr/lib/python2.7/site-packages/nflgame/__init__.py", line 229, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable

**Comment by bubbajones69** [comment]
SOLUTION - nflgame schedule update - 

run:
\nflgame>python update_sched.py --year 2017

this will update the schedule which solved for me -
