### ISSUE TITLE
exception running update.py -players

### ISSUE THREAD

**Issue by bubbajones69** [rbrnk/fflproject#39]
getting an error related to Xavier Brown when trying to import players for 2017

Updating local FF database....
New player: 00-0029713 Xavier Brown (0 - 0)
Traceback (most recent call last):
  File "update.py", line 867, in <module>
    main()
  File "update.py", line 69, in main
    update_players(year, week, weektype)
  File "update.py", line 374, in update_players
    cur.execute(query)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1366, "Incorrect integer value: '' for column 'height' at row 1")

**Comment by bubbajones69** [comment]
I hacked update.py to ensure height, weight and number were an int and got past the above - but not sure about this one - 

Updating local FF database....
Added: 0 players.
Updated: 7549 players.
Updating esbids from api.fantasy.nfl.com using year 2017, week 1
Traceback (most recent call last):
  File "update.py", line 874, in <module>
    main()
  File "update.py", line 69, in main
    update_players(year, week, weektype)
  File "update.py", line 387, in update_players
    update_esbids(year,week)
  File "update.py", line 402, in update_esbids
    cur.execute(query)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'esbid' in 'where clause'")

**Comment by nickfrerichs** [comment]
Do you have an esbid column in your player table?  It was added last Fall by the db_upgrade.py file in the upgrade to DB version 1.3. You could try running db_upgrade.py, it should bring your DB inline with whatever version of code you're on.

Otherwise, you could print the query string right before line 402 to see the actual SQL query.

**Comment by bubbajones69** [comment]
that fixed it - closing
